import Head from 'next/head';
import { getSession } from "next-auth/client";
import Header from '../components/Header';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widget from '../components/Widget';



export default function Home({ session }) {

  if(!session) return <Login />

  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex">
        <Sidebar />
        <Feed />
        <Widget />
      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  // get the user
  const session = await getSession(context);

  /*let posts = db.collection('posts').orderBy('timestamp', 'desc').get();

  const docs = (await posts).docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))*/
 
  return {
    props : {
      session,
      //post: docs,
    }
  }
}