import Head from 'next/head';
import { getSession } from "next-auth/client";
import Header from '../components/Header';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';


export default function Home({ session }) {
  if(!session) return <Login />
  return (
    <div className="h-screen bg-gary-100 overflow-hidden">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex">
        <Sidebar />
        <Feed />
        {/* Widgets */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  // get the user
  const session = await getSession(context);
  return {
    props : {
      session
    }
  }
}